import os
import requests

def generate_tts(text):
    # ✅ Get API key from environment (set in GitHub Actions secrets)
    api_key = os.getenv("ELEVENLABS_KEY1")
    if not api_key:
        raise ValueError("❌ ELEVENLABS_KEY1 not found. Did you set it in GitHub Secrets?")

    # ✅ Save audio in the same folder as this script
    base_dir = os.path.dirname(os.path.abspath(__file__))
    audio_path = os.path.join(base_dir, "audio.mp3")

    url = "https://api.elevenlabs.io/v1/text-to-speech/YOUR_VOICE_ID"

    headers = {
        "Accept": "audio/mpeg",
        "Content-Type": "application/json",
        "xi-api-key": api_key
    }

    data = {
        "text": text,
        "voice_settings": {
            "stability": 0.5,
            "similarity_boost": 0.7
        }
    }

    print("🎤 Generating audio from ElevenLabs...")
    response = requests.post(url, headers=headers, json=data)

    if response.status_code == 200:
        with open(audio_path, "wb") as f:
            f.write(response.content)
        print(f"✅ Audio saved at {audio_path}")
        return audio_path
    else:
        raise RuntimeError(f"❌ Failed to generate audio: {response.status_code}, {response.text}")

if __name__ == "__main__":
    # Example usage
    sample_text = "Hello, this is a test voiceover generated by ElevenLabs API."
    generate_tts(sample_text)
