name: Astrology Shorts Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate viral script
        run: python generate_script.py
        env:
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}

      - name: Generate TTS audio (with failover keys)
        run: python generate_tts.py
        env:
          ELEVENLABS_KEY1: ${{ secrets.ELEVENLABS_KEY1 }}
          ELEVENLABS_KEY2: ${{ secrets.ELEVENLABS_KEY2 }}
          ELEVENLABS_KEY3: ${{ secrets.ELEVENLABS_KEY3 }}

      - name: Create video
        run: python create_video.py
        env:
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}

      - name: Upload to YouTube
        run: python upload.py
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          SERIES1_PLAYLIST_ID: ${{ secrets.SERIES1_PLAYLIST_ID }}
          SERIES2_PLAYLIST_ID: ${{ secrets.SERIES2_PLAYLIST_ID }}
