name: Astrology Shorts Automation

on:
  workflow_dispatch: # Run manually
  schedule:
    - cron: "0 */6 * * *" # every 6 hours

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate viral script
        run: python generate_script.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}

      - name: Generate TTS audio
        run: python generate_tts.py
        env:
          ELEVENLABS_KEY1: ${{ secrets.ELEVENLABS_KEY1 }}
          ELEVENLABS_KEY2: ${{ secrets.ELEVENLABS_KEY2 }} # fallback key (optional)

      - name: Create video
        run: python create_video.py
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}

      - name: Upload to YouTube
        run: python upload.py
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          SERIES1_PLAYLIST_ID: ${{ secrets.SERIES1_PLAYLIST_ID }} # Horoscope
          SERIES2_PLAYLIST_ID: ${{ secrets.SERIES2_PLAYLIST_ID }} # Numerology
