name: Astrology Shorts Automation

on:
  workflow_dispatch: # Run manually from GitHub Actions tab
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours (adjust if needed)

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests moviepy google-api-python-client google-auth-oauthlib google-auth-httplib2

      - name: Generate TTS audio
        run: python generate_tts.py
        env:
          ELEVENLABS_KEY1: ${{ secrets.ELEVENLABS_KEY1 }}

      - name: Create video
        run: python create_video.py

      - name: Upload to YouTube
        run: python upload.py
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          SERIES1_PLAYLIST_ID: ${{ secrets.SERIES1_PLAYLIST_ID }}
          SERIES2_PLAYLIST_ID: ${{ secrets.SERIES2_PLAYLIST_ID }}

      - name: Upload video artifact (backup)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: final_video
          path: final_video.mp4
