name: Batch 1 - Generate and Upload First 6 (6 AM)

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 6:00 AM IST (00:30 UTC)
    - cron: '30 0 * * *'

permissions:
  contents: read

jobs:
  batch1:
    name: Generate 12 Videos + Upload First 6
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick fonts-noto
          if [ -f /etc/ImageMagick-6/policy.xml ]; then
            sudo sed -i 's/<policy domain="path" rights="none" pattern="@\*"\/>/<!-- disabled -->/g' /etc/ImageMagick-6/policy.xml
          fi

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install chromium
          playwright install-deps chromium

      - name: Run Batch 1 (Generate + Upload first 6)
        env:
          PYTHONUNBUFFERED: "1"
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: |
          echo "🌅 BATCH 1: Generating 12 videos and uploading first 6"
          python orchestrate.py first

      - name: Upload remaining 6 videos for Batch 2
        uses: actions/upload-artifact@v4
        with:
          name: remaining-videos-${{ github.run_number }}
          path: outputs/*.mp4
          retention-days: 1

      - name: Summary
        run: |
          echo "## 🌅 Batch 1 Complete (6 AM)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Generated: 12 videos" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Uploaded: First 6 rashis" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Saved: Remaining 6 for Batch 2" >> $GITHUB_STEP_SUMMARY
